### ISSUE TITLE
EID time counter initialization

### ISSUE THREAD

**Issue by samueleforconi** [NordicPlayground/nrf5-sdk-for-eddystone#8]
In file `eddystone_security.c`, at line `148`,  `413`, `488` the Eddystone EID time counter is initialized at a fixed value of `65280`   ( i.e.  `m_security_slot[slot_no].timing.seconds = 65280` ).
As it is written in the [Eddystone EID Implementation Guidelines](https://github.com/google/eddystone/blob/master/eddystone-eid/eid-computation.md) 

> beacons should initialize their time counter at registration to a value close to the roll-over of the temporary key (i.e., time counter value mod 65536 of around 65280)

To me, this example means that if k_scaler = 16 (2^16 = 65536), the beacon should initialize the time counter to 65280, but this initialization value should be different if the k_scaler is 12 or another value.
I think that the time counter should be initialized to a value close to 2^k_scaler, not to a fixed value of 65280.

**Comment by tonywu-nordicsemi** [comment]
the temporary key roll-over is a static value of 65536 seconds because the [temporary key](https://github.com/google/eddystone/blob/master/eddystone-eid/eid-computation.md#computing-the-temporary-key) is obtained by AES-128 encyrption of 16 bytes of data that contains some static values (salts and padding) and a time-dependent top 16 bits of the beacon timer. Only the time-dependent top 16-bits of the beacon timer will change, and it changes every 65536 (2^16) seconds when the bottom 16-bit of the beacon timer has rolled over. This means that the temporary key will change (aka roll over) every 65536 seconds. 

The k scaler determines how often the EID changes and does not effect how often the temporary key rolls over. Also the k scaler can only have a maximum value of 15 according to the specifications:

> The rotation period exponent. This is a value between 0 and 15, corresponding to a power-of-two scaler on the time counter. When the scaler value is K, the beacon will generate a new identifier every 2^K seconds.

Hope this helps :).

**Comment by samueleforconi** [comment]
Thanks for the explanation Tony. I missed that it was referred to the temporary key roll-over...
